### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by Kickball** [msmith91/google_traffic#4]
When running the current version of the script I encounter an error. This error is caught by the try-catch in the main section and the following error is thrown:

`Missing argument: needs either "to_work" or "from_work"` 

However when I remove the try-catch statement the following error is thrown:

```
Traceback (most recent call last):
File "map.py", line 56, in <module>
    time_list = googleMaps().get_time(work,home,model)
  File "map.py", line 25, in get_time
    time_estimate = json_dict['routes'][0]['legs'][0]['duration_in_traffic']['value'] /60
IndexError: list index out of range
```

The url which I'm using is:
https://maps.googleapis.com/maps/api/directions/json?origin=456+Other+Place+Chicago+IL&destination=123+Park+Place+Chicago+IL&key=REDACTED&departure_time=now&traffic_model=best_guess

**Comment by Kickball** [comment]
I have managed to fix the error which was that the project my API key was attached to did not have Google Maps Directions API enabled.
